CREATE TABLE weather (
edt                       date,
max_temperature_f         integer,
mean_temperature_f	  integer,
min_temperature_f         integer,
max_dew_point_f           integer,
mean_dew_point_f          integer,
min_dew_point_f		  integer,
max_humidity              integer,
mean_humidity             integer,
min_humidity              integer,
max_sea_level_pressure    float,
mean_sea_level_pressure   float,
min_sea_level_pressure    float,
max_visibility_miles      integer,
mean_visibility_miles     integer,
min_visibility_miles      integer,
max_wind_speed_mph        integer,
mean_wind_speed_mph       integer,
max_gust_speed_mph        integer,
precipitation             float,
cloud_cover               integer,
events                    varchar(30),
wind_dir_degrees          integer
);
